services:
  data:
    build:
      context: ./
      dockerfile: data.local.Dockerfile
    networks:
      my-net:
        aliases:
          - my-proj-data
    container_name: data
    restart: unless-stopped
    ports:
      - 8686:8080
    environment:
      - DB_HOST=my-mysql
      - DB_USER=mydbuser
      - DB_PASSWORD=Password01!
      - DB_DBNAME=mydb
      - DB_PORT=3306
    stdin_open: true
    tty: true

  vue:
    build:
      context: ./
      dockerfile: vue.local.Dockerfile
    networks:
      my-net:
        aliases:
          - my-proj-vue
    container_name: vue
    restart: unless-stopped
    ports:
      - 7676:7070
    environment:
      - VITE_DATA_PARTY_ENDPOINT=http://my-proj-data:8080/api
    stdin_open: true
    tty: true

  authapi:
    build:
      context: ./
      dockerfile: authapi.local.Dockerfile
    networks:
      my-net:
        aliases:
          - my-proj-authapi
    container_name: authapi
    restart: unless-stopped
    ports:
      - 6666:6060
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentLocal
      - ASPNETCORE_HTTP_PORTS=6666
    stdin_open: true
    tty: true

  authportal:
    build:
      context: ./
      dockerfile: authportal.local.Dockerfile
    networks:
      my-net:
        aliases:
          - my-proj-authportal
    container_name: authportal
    restart: unless-stopped
    ports:
      - 5656:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentLocal
      - ASPNETCORE_HTTP_PORTS=5656
    stdin_open: true
    tty: true

networks:
  my-net:
    name: my-proj
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"