@WebApi_HostAddress = http://localhost:5858

GET {{WebApi_HostAddress}}/api/users

###

GET {{WebApi_HostAddress}}/api/users/20b7fff6-5650-424a-8218-f82d7c6b7e44

###

POST {{WebApi_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "Shengshuai Zhou",
  "email": "zss@qq.com",
  "avatarUrl": "https://img.wxcha.com/m00/34/de/4cef0b011eb3386016b1f9c2e408bcc6.jpg?down"
}

###

PUT {{WebApi_HostAddress}}/api/users/e93e1585-f2bc-46c1-b701-c62bcdf4a516
Content-Type: application/json

{
  "name": "Shengshuai Zhou",
  "email": "zss@qq.com",
  "avatarUrl": "https://img.wxcha.com/m00/34/de/4cef0b011eb3386016b1f9c2e408bcc6.jpg"
}

###

@id=string
DELETE {{WebApi_HostAddress}}/api/users/{{id}}

###
