/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNotification: typeof import('./src/components/AppNotification.vue')['default']
    AppNotifications: typeof import('./src/components/AppNotifications.vue')['default']
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElText: typeof import('element-plus/es')['ElText']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NotificationPopup: typeof import('./src/components/NotificationPopup.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    PageInternal: typeof import('./src/components/PageInternal.vue')['default']
    PartListViewComp: typeof import('./src/components/PartListViewComp.vue')['default']
    PO: typeof import('./src/components/PO.vue')['default']
    POItem: typeof import('./src/components/POItem.vue')['default']
    POList: typeof import('./src/components/POList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewError: typeof import('./src/components/ViewError.vue')['default']
    ViewLoading: typeof import('./src/components/ViewLoading.vue')['default']
    ViewPage: typeof import('./src/components/ViewPage.vue')['default']
    ViewPageInternal: typeof import('./src/components/ViewPageInternal.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
