/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNotifications: typeof import('./src/components/AppNotifications.vue')['default']
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    ViewError: typeof import('./src/components/ViewError.vue')['default']
    ViewLoading: typeof import('./src/components/ViewLoading.vue')['default']
    ViewPage: typeof import('./src/components/ViewPage.vue')['default']
    ViewPageInternal: typeof import('./src/components/ViewPageInternal.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
